version: '2.1'

services:

    proxy:
        image: nginx:latest
        container_name: proxy
        build: ./proxy
        depends_on:
            - gutenberg
        volumes:
          - ./proxy/nginx.conf:/etc/nginx/nginx.conf
          - st:/etc/nginx/html/static
        ports: 
          - 80:80

    postgres:
        image: postgres:9.5
        ports:
          - 5432:5432
        environment: 
            POSTGRES_DB: 'gutenberg'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: '123'
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
            interval: 10s
            timeout: 5s
            retries: 5
        volumes: 
            - postgres_data:/var/lib/postgresql


    gutenberg:
        image: "gutenberg"
        container_name: gutenberg
        build: ./project
        volumes: 
            - st:/st
        depends_on:
            postgres:
                condition: service_healthy
        ports: 
            - 8000:80
volumes: 
    postgres_data:
    st: