version: '2.1'

services:

    postgres:
        image: postgres:latest
        ports:
          - "5432:5432"
        environment: 
            POSTGRES_DB: 'gutenberg'
            POSTGRES_USER: 'gutenberg'
            POSTGRES_PASSWORD: '123'
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
            interval: 10s
            timeout: 5s
            retries: 5
        volumes: 
            - postgres:/var/lib/postgresql


    gutenberg:
        image: "gutenberg"
        container_name: gutenberg
        build: .
        depends_on:
            postgres:
                condition: service_healthy
        ports: 
            - 8000:80
volumes: 
    postgres: